# Site settings
course_name: CS60112 - Information and System Security
course_description: "Almost any non-trivial system that exists out there (and that you might build) utilizes some kind of valuable resource, which might be data, intellectual property or physical resources. In addition to utilizing the resource, the system must also ensure that it protects the resource from unintended use."

course_semester: "Spring 2025"

baseurl: "/InfoSec-2025" # the subpath of your site, e.g. /blog/
url: "https://Kronos-192081.github.io/" # the base hostname & protocol for your site

schoolname: "CSE, IIT Kharagpur"
schoolurl: "https://cse.iitkgp.ac.in" 

address: |
    Kharagpur
    West Bengal
    India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
